# Generated by Django 4.2.18 on 2025-02-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_delete_writing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
    ]
