# Generated by Django 4.2.18 on 2025-02-19 22:18

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='/media/images/blank.jpg', upload_to=blog.models.get_upload_path, verbose_name='Uploaded Image'),
        ),
    ]
