# Generated by Django 4.2.18 on 2025-02-23 02:45

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='/images/blank.jpg', null=True, upload_to=blog.models.get_upload_path, verbose_name='Image'),
        ),
    ]
