# Generated by Django 4.2.18 on 2025-03-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_create_date_blog_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='create_date',
        ),
    ]
