# Generated by Django 4.2.18 on 2025-02-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinfo_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'User_Info'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='website',
        ),
    ]
