# Generated by Django 5.2 on 2025-04-16 21:41

import chirps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0003_alter_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chirps.models.get_upload_path, verbose_name='Image'),
        ),
    ]
