# Generated by Django 4.2.18 on 2025-02-11 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name_plural': 'Products'},
        ),
        migrations.CreateModel(
            name='Birdies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='images/blank.jpg', upload_to=posts.models.get_upload_path)),
                ('size', models.CharField(choices=[('Extra-Small', 'Extra-Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra-Large', 'Extra-Large')], max_length=30)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Birds',
                'ordering': ['name'],
            },
        ),
    ]
