# Generated by Django 4.2.18 on 2025-02-11 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_description_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_product_options_birdies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(unique=True)),
                ('message_html', models.TextField(editable=False)),
                ('group', models.OneToOneField(blank=True, default='None', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'message')},
            },
        ),
    ]
