# Generated by Django 4.2.18 on 2025-02-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_birdies_options_alter_product_options_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(unique=True),
        ),
    ]
