# Generated by Django 4.2.18 on 2025-03-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_user_message_group',
        ),
    ]
