# Generated by Django 4.2.18 on 2025-03-20 16:12

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_unique_user_message_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts/blank.jpg', upload_to=posts.models.get_upload_path),
        ),
    ]
