# Generated by Django 4.2.18 on 2025-02-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_shelves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelves',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
