# Generated by Django 4.2.18 on 2025-02-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_alter_shelves_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShelfList',
        ),
    ]
