# Generated by Django 4.2.18 on 2025-03-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_alter_shelves_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelves',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
