# Generated by Django 4.2.18 on 2025-03-18 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelf', '0006_shelves_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelves',
            name='liked',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
