# Generated by Django 4.2.18 on 2025-04-10 00:45

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('shelf', '0006_alter_shelves_options_shelves_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelves',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='shelves',
            name='year',
            field=models.IntegerField(blank=True, default='––', null=True),
        ),
    ]
