# Generated by Django 5.2 on 2025-04-16 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0008_shelves_liked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelves',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='shelf_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
