# Generated by Django 5.2 on 2025-04-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0009_alter_shelves_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelves',
            name='pages',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='shelves',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='.00', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='shelves',
            name='weight',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='shelves',
            name='year',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
