# Generated by Django 4.2.18 on 2025-03-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_comment_create_date_comment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
