# Generated by Django 4.2.18 on 2025-03-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_rename_author_comment_user_alter_comment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='message',
        ),
    ]
