# Generated by Django 4.2.18 on 2025-03-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
